-- ==============================================================================
-- GUMBALLZ SUPABASE MASTER SCHEMA (COMPLETE V2)
-- Combined from ALL migration files in the project.
-- Usage: Run this in Supabase SQL Editor to set up the ENTIRE database.
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 1. Table: mod_keys (Main Key System for Mod Menu)
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS mod_keys (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    key_value TEXT UNIQUE NOT NULL,
    key_type TEXT NOT NULL CHECK (key_type IN ('FREE', 'PREMIUM', 'free', 'premium')), -- Case insensitive support
    
    -- Timing fields
    created_date DATE,
    duration_days INTEGER,
    expires_at TIMESTAMPTZ NOT NULL,
    
    -- Payment fields
    price_vnd INTEGER,
    
    -- Link fields (for yeulink)
    short_link TEXT,
    destination_url TEXT,
    
    -- Status fields
    is_active BOOLEAN DEFAULT false,
    usage_count INTEGER DEFAULT 0,
    last_used_at TIMESTAMPTZ,
    
    -- Device binding fields (HWID)
    device_id TEXT,
    device_bound_at TIMESTAMPTZ,
    max_devices INTEGER DEFAULT 1,
    
    -- Security
    verification_token TEXT,
    
    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for mod_keys
CREATE INDEX IF NOT EXISTS idx_mod_keys_key_value ON mod_keys(key_value);
CREATE INDEX IF NOT EXISTS idx_mod_keys_key_type ON mod_keys(key_type);
CREATE INDEX IF NOT EXISTS idx_mod_keys_created_date ON mod_keys(created_date);
CREATE INDEX IF NOT EXISTS idx_mod_keys_is_active ON mod_keys(is_active);
CREATE INDEX IF NOT EXISTS idx_mod_keys_device_id ON mod_keys(device_id);

-- ------------------------------------------------------------------------------
-- 2. Table: roblox_keys (Dedicated Key System for Roblox Scripts)
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS roblox_keys (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    key_value TEXT UNIQUE NOT NULL,
    key_type TEXT NOT NULL CHECK (key_type IN ('free', 'premium', 'FREE', 'PREMIUM')),
    category TEXT NOT NULL DEFAULT 'roblox', -- 'roblox'
    
    -- Timing
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    
    -- Usage/Status
    is_used BOOLEAN DEFAULT FALSE,
    
    -- Advanced Metadata (Stores HWID, Transaction ID, Source, etc.)
    metadata JSONB DEFAULT '{}'::jsonb
);

-- Indexes for roblox_keys
CREATE INDEX IF NOT EXISTS roblox_keys_value_idx ON roblox_keys (key_value);

-- ------------------------------------------------------------------------------
-- 3. Table: transactions (Payment History & Key Generation Trigger)
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS transactions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id TEXT, -- Can be null for guest transactions
    amount INTEGER NOT NULL,
    description TEXT, -- Usually the Transaction Content (e.g., KEY123456)
    status TEXT DEFAULT 'pending', -- 'pending', 'success', 'failed'
    rewarded BOOLEAN DEFAULT FALSE, -- To prevent double rewards
    
    -- Metadata stores what the user bought (key type, duration, etc.)
    metadata JSONB DEFAULT '{}'::jsonb,
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for transactions
CREATE INDEX IF NOT EXISTS idx_transactions_description ON transactions(description);
CREATE INDEX IF NOT EXISTS idx_transactions_status ON transactions(status);

-- ------------------------------------------------------------------------------
-- 4. Table: mod_configs (Remote Configuration)
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS mod_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_name TEXT NOT NULL,
    config_data TEXT NOT NULL, 
    version_code INT DEFAULT 1,
    is_active BOOLEAN DEFAULT FALSE,
    last_modified_by TEXT DEFAULT 'System',
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- ------------------------------------------------------------------------------
-- 5. Table: downloads (APK/File Hosting Links)
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS downloads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    image_url TEXT, 
    download_url TEXT NOT NULL, 
    version TEXT,
    file_size TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- ------------------------------------------------------------------------------
-- 6. Trigger: Auto-Update `updated_at` Column
-- ------------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply to relevant tables
DROP TRIGGER IF EXISTS update_mod_keys_time ON mod_keys;
CREATE TRIGGER update_mod_keys_time BEFORE UPDATE ON mod_keys FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_transactions_time ON transactions;
CREATE TRIGGER update_transactions_time BEFORE UPDATE ON transactions FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_mod_configs_time ON mod_configs;
CREATE TRIGGER update_mod_configs_time BEFORE UPDATE ON mod_configs FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ------------------------------------------------------------------------------
-- 7. Row Level Security (RLS) Policies
-- ------------------------------------------------------------------------------

-- Enable RLS on all tables
ALTER TABLE mod_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE roblox_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE mod_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE downloads ENABLE ROW LEVEL SECURITY;

-- Policy: SERVICE ROLE (Backend) has FULL ACCESS to everything
-- This is critical for your API routes to work correctly.
CREATE POLICY "Service Role Full Access mod_keys" ON mod_keys FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Service Role Full Access roblox_keys" ON roblox_keys FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Service Role Full Access transactions" ON transactions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Service Role Full Access mod_configs" ON mod_configs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Service Role Full Access downloads" ON downloads FOR ALL USING (true) WITH CHECK (true);

-- Policy: PUBLIC READ (Careful! Only for non-sensitive data)
-- Allow public to read CONFIGS (Active only)
CREATE POLICY "Public Read Active Configs" ON mod_configs FOR SELECT TO public USING (true);
-- Allow public to read DOWNLOADS (Active only)
CREATE POLICY "Public Read Active Downloads" ON downloads FOR SELECT TO public USING (is_active = true);
-- Allow public to read VALID ROBLOX KEYS (Needed for script validation if not using Service Role, but usually API handles this)
CREATE POLICY "Public Read Roblox Keys" ON roblox_keys FOR SELECT TO public USING (true);


-- ------------------------------------------------------------------------------
-- 8. Seed Data (Default Values)
-- ------------------------------------------------------------------------------

-- Insert default config if table is empty
INSERT INTO mod_configs (config_name, config_data, is_active, version_code)
SELECT 'LQM Default', 'Hack Map (0x5154A00)|5154A00|D2800036;Cam Gần|5EF319C|1E2F1001;Cam Xa|5EF3198|1E2F9000;Cam Siêu Xa|5EF31A8|1E201001;Hiện Tên Cấm Chọn|5BF6B8C|D2800037;Hiện LSĐ|5A26C64|D2800020D65F03C0;Hiện Avatar|5A01A30|D2800000D65F03C0;Hiện Bổ Trợ|5D8415C|D503201F;Hiện Ulti 1|5BECAE4|D503201F;Hiện Ulti 2|5BECB88|52800033;Hiện Rank|5CB0AC4|D503201F;Fix FPS 1|5C34744|D65F03C0;Fix FPS 2|5C34644|D65F03C0;3 Nút|5C28638|52800020D65F03C0;Aim|61A36D0|528000E3D65F03C0', TRUE, 1
WHERE NOT EXISTS (SELECT 1 FROM mod_configs);
