-- Create table for Downloads
CREATE TABLE IF NOT EXISTS downloads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    image_url TEXT, -- URL to the image/icon
    download_url TEXT NOT NULL, -- URL to the APK/File
    version TEXT,
    file_size TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS Policies
ALTER TABLE downloads ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can read active downloads" ON "downloads"
AS PERMISSIVE FOR SELECT
TO public
USING (is_active = true);

CREATE POLICY "Authenticated users can insert downloads" ON "downloads"
AS PERMISSIVE FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Authenticated users can update downloads" ON "downloads"
AS PERMISSIVE FOR UPDATE
TO authenticated
USING (true);

CREATE POLICY "Authenticated users can delete downloads" ON "downloads"
AS PERMISSIVE FOR DELETE
TO authenticated
USING (true);
